# Generated by Django 3.1.2 on 2020-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=45)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('app_productdesc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=45)),
                ('creationtime', models.DateTimeField()),
            ],
        ),
    ]
